name: Generate GPG Key Pair

on:
  push:
    branches:
      - master

jobs:
  generate_gpg_key:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GPG Key
        run: |
          # Generate the GPG key pair (Note: The passphrase is set to empty here, which is not secure)
          gpg --batch --passphrase '' --quick-gen-key "siddharth <sharmasid2398@gmail.com>"

          # Print the public key
          gpg --armor --export "your@email.com"

          # Print the private key
          gpg --armor --export-secret-keys "sharmasid2398@gmail.com"

