name: DevSecOps Pipeline

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check_dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace 'x' with the desired Python version (e.g., 3.8)

      - name: Install dockerfile2json
        run: pip install dockerfile2json

      # Convert Dockerfile to JSON format
      - name: Convert Dockerfile to JSON
        run: dockerfile2json ./Dockerfile > Dockerfile.json

      - name: Run Dockerfile checker
        run: |
          python dockerfile_checker.py > policy_report.txt
          
      # Publish the policy_report.txt as an artifact
      - name: Publish Policy Report
        uses: actions/upload-artifact@v2
        with:
          name: policy-report
          path: ./policy_report.txt

  gitleaks_scan:
    name: Gitleaks Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download Gitleaks Binary
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.17.0/gitleaks_8.17.0_linux_x64.tar.gz
          tar -xzf gitleaks_8.17.0_linux_x64.tar.gz -C /tmp
          chmod +x /tmp/gitleaks
      - name: Move Gitleaks Binary to /usr/local/bin
        run: sudo mv /tmp/gitleaks /usr/local/bin/

      - name: Debug
        run: ls /usr/local/bin/
      - name: help
        run: gitleaks --help

      - name: Run Gitleaks Scan
        run: |
          # Replace 'https://github.com/owner/repo.git' with the actual repository URL
          REPO_URL='https://github.com/sidwar76/hashedin.git'
          CUSTOM_RULES='{
            "rules": [
              {
                "regex": "(password|api_key|secret)",
                "description": "Potential sensitive information",
                "tags": ["high_severity"]
              },
              {
                "regex": "(access_key|private_key)",
                "description": "Potential access keys",
                "tags": ["high_severity"]
              },
              {
                "file": "\\.env|config\\.json",
                "description": "Potential configuration files",
                "tags": ["medium_severity"]
              }
            ]
          }'
          # Save custom rules to a temporary file
          echo "$CUSTOM_RULES" > CUSTOM_RULES.json
          # Run Gitleaks scan with custom rules and the repository URL
          gitleaks detect -c gitleaks.toml --report-path gitleaks-report.json -f json 
      - name: Upload Gitleaks Scan Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: gitleaks-scan-report
          path: gitleaks-report.json

  build_and_scan:
    name: Build, Scan, and Sign Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t sidwar/myapp:${{ github.sha }} .

      - name: Docker Logout
        run: docker logout

      - name: Docker Login
        run: |
          # Log in to Docker Hub or the desired container registry using environment variables
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: |
          docker push sidwar/myapp:${{ github.sha }}
      - name: Vulnerability Scanning
        run: |
          # Use Trivy for vulnerability scanning and capture the output in trivy-report.json
          #docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/root/ aquasec/trivy:latest image sidwar/myapp:${{ github.sha }} > trivy-report.json
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/root/ aquasec/trivy:latest image --vuln-type="os,library" sidwar/myapp:${{ github.sha }}> trivy-report.json
        # Publish the vulnerability scanning report as an artifact
      - name: Publish Vulnerability Scanning Report
        uses: actions/upload-artifact@v2
        with:
            name: vulnerability-report
            path: ./trivy-report.json

      - name: Verify and Sign Image
        run: |
          # Verify if the Docker image is signed
          if docker trust inspect --pretty myapp:${{ github.sha }} &> /dev/null; then
            echo "Image is already signed."
          else
            echo "Image is not signed. Signing the image using cosign..." > sign-image-report.txt
          fi
        # Publish the sign image report as an artifact
      - name: Publish Sign Image Report
        uses: actions/upload-artifact@v2
        with:
            name: sign-image-report
            path: ./sign-image-report.txt

      - name: pull TruffleHog
        run: docker pull gesellix/trufflehog

      - name: Run TruffleHog
        run: |
          # Run TruffleHog and capture the output in trufflehog-report.json
          docker run -t gesellix/trufflehog --json https://github.com/sidwar76/OPA.git > trufflehog-report.json
        # Publish the TruffleHog report as an artifact
      - name: Publish TruffleHog Report
        uses: actions/upload-artifact@v2
        with:
            name: trufflehog-report
            path: ./trufflehog-report.json
