name: Docker CI

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t sidwar/myapp:latest .
          docker push sidwar/myapp:latest
      
      - name: Install cosign
        run: |
          curl -LO https://github.com/sigstore/cosign/releases/download/v1.2.1/cosign-linux-amd64
          chmod +x cosign-linux-amd64
          sudo mv cosign-linux-amd64 /usr/local/bin/cosign

      - name: Write signing key to disk
        run: openssl genpkey -algorithm RSA -out cosign.key

      - name: Load the unencrypted private key
        run: cosign key load cosign.key
      
      - name: Sign the published Docker image
        env:
          COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        run: cosign sign --key cosign.key sidwar/myapp:latest

