name: Docker Content Trust Signing

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  sign_docker_image:
    name: Sign and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker CLI
        uses: docker/setup-docker@v1

      - name: Save Private Key to File
        run: echo "${{ secrets.DOCKER_PRIVATE_KEY }}" > private_key.pem

      - name: Load Private Key with Docker Trust
        run: docker trust key load private_key.pem --name Jeff
        env:
          DOCKER_CONTENT_TRUST: "1"

      - name: Build Docker Image
        run: docker build -t sidwar/myapp:latest .

      - name: Add Signer and Sign Image
        run: |
          expect <<EOF
          spawn docker trust signer add --key jeff.pub Jeff sidwar/myapp:latest
          expect "Enter passphrase for new signer key with ID jeff:"
          send "${{ secrets.COMMON_PASSPHRASE }}\n"
          expect "Successfully added signer: jeff"
          spawn docker trust sign sidwar/myapp:latest
          expect "Enter passphrase for signer key with ID jeff:"
          send "${{ secrets.COMMON_PASSPHRASE }}\n"
          expect "Successfully signed docker.io/sidwar/myapp:latest"
          EOF
        env:
          DOCKER_CONTENT_TRUST: "1"

      - name: Push Docker Image
        run: docker push sidwar/myapp:latest
        env:
          DOCKER_CONTENT_TRUST: "1"

