name: Build and sign Docker image

on:
  push:
    branches:
      - master

jobs:
  build_and_sign:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set up GPG keys
        run: |
          # Read the private key from the file
          cat private_key.asc | gpg --import -
        working-directory: ${{ github.workspace }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and sign Docker image
        run: |
          # Create and use the Buildx builder
          docker buildx create --use

          # Build the Docker image with multi-platform support and tag with GitHub SHA
          docker buildx build --platform linux/amd64,linux/arm64 --push -t sidwar/myapp:${{ github.sha }} .
        env:
          # Set environment variables for the Docker build command
          DOCKER_CLI_ACI: 1
          DOCKER_BUILDKIT: 1
          DOCKER_CONTENT_TRUST: 1
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          
          
      - name: Import public key for verification
        run: |
          # Read the public key from the file and import it
          gpg --import public_key.asc

      - name: Verify GPG signature of Docker image
        run: |
          # Pull the Docker image with the GPG signature
          docker pull sidwar/myapp:${{ github.sha }}

          # Verify the image against the signature
          docker trust verify --signing-key 37800B1CA821E8DBA0E02C6609A3E699F359FC6B sidwar/myapp:${{ github.sha }}


