name: Build, Scan, and Sign Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_scan_sign_image:
    name: Build, Scan, Sign, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t sidwar/myapp:${{ github.sha }} .

      - name: Docker Logout
        run: docker logout

      - name: Docker Login
        run: |
          # Log in to Docker Hub or the desired container registry using environment variables
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Check if Keys Exist
        id: check_keys
        run: |
          if [ -z "${{ secrets.DOCKER_CONTENT_TRUST_PRIVATE_KEY }}" ] || [ -z "${{ secrets.DOCKER_CONTENT_TRUST_PUBLIC_KEY }}" ]; then
            echo "Generating new keys..."
            DOCKER_CONTENT_TRUST_PASSPHRASE="${{ secrets.PASSPHRASE }}"
            export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE="$DOCKER_CONTENT_TRUST_PASSPHRASE"
            docker trust key generate my_signing_key
            # Store the generated public and private keys as secrets
            echo "$(base64 private_key_file.key)" >> private_key_secret.txt
            echo "$(base64 my_signing_key.pub)" >> public_key_secret.txt
            echo "::set-output name=keys_exist::false"
            # Create the secrets using the GitHub API
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            REPO_FULLNAME=$(echo $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')
            PRIVATE_KEY_CONTENT=$(base64 private_key_secret.txt)
            PUBLIC_KEY_CONTENT=$(base64 public_key_secret.txt)
            curl -X PUT \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"encrypted_value\":\"$PRIVATE_KEY_CONTENT\",\"key_id\":null}" \
              "https://api.github.com/repos/$REPO_FULLNAME/actions/secrets/DOCKER_CONTENT_TRUST_PRIVATE_KEY"
            curl -X PUT \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"encrypted_value\":\"$PUBLIC_KEY_CONTENT\",\"key_id\":null}" \
              "https://api.github.com/repos/$REPO_FULLNAME/actions/secrets/DOCKER_CONTENT_TRUST_PUBLIC_KEY"
            
            echo "Docker Content Trust secrets have been created."
          else
            echo "Keys exist."
            # Load the existing public and private keys from secrets
            echo "${{ secrets.DOCKER_CONTENT_TRUST_PRIVATE_KEY }}" | base64 -d > private_key_file.key
            echo "${{ secrets.DOCKER_CONTENT_TRUST_PUBLIC_KEY }}" | base64 -d > my_signing_key.pub
            docker trust key load private_key_file.key --name my_signing_key --key my_signing_key.pub
            echo "::set-output name=keys_exist::true"
          fi

      - name: Sign the Docker Image
        if: steps.check_keys.outputs.keys_exist == 'true'
        run: |
          DOCKER_CONTENT_TRUST_PASSPHRASE="${{ secrets.PASSPHRASE }}"
          echo "$DOCKER_CONTENT_TRUST_PASSPHRASE" > pass.txt
          chmod 600 pass.txt
          docker trust sign -k my_signing_key --key my_signing_key.pub --passphrase-file pass.txt sidwar/myapp:${{ github.sha }}
          rm -f pass.txt

      - name: Push Docker Image
        run: |
          docker push sidwar/myapp:${{ github.sha }}

      - name: Vulnerability Scanning
        run: |
          # Use Trivy for vulnerability scanning and capture the output in trivy-report.json
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/root/ aquasec/trivy:latest image --vuln-type="os,library" sidwar/myapp:${{ github.sha }} > trivy-report.json
        # Publish the vulnerability scanning report as an artifact
      - name: Publish Vulnerability Scanning Report
        uses: actions/upload-artifact@v2
        with:
          name: vulnerability-report
          path: ./trivy-report.json

      # Add other steps for your scanning process (if any)

      - name: Verify the Signed Image
        if: steps.check_keys.outputs.keys_exist == 'true'
        run: docker trust verify sidwar/myapp:${{ github.sha }}
