name: Build, Scan, and Sign Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_scan_sign_image:
    name: Build, Scan, Sign, and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t sidwar/myapp:${{ github.sha }} .

      - name: Docker Logout
        run: docker logout

      - name: Docker Login
        run: |
          # Log in to Docker Hub or the desired container registry using environment variables
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Enable Docker Content Trust
        run: export DOCKER_CONTENT_TRUST=1

      - name: Vulnerability Scanning
        run: |
          # Use Trivy for vulnerability scanning and capture the output in trivy-report.json
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/root/ aquasec/trivy:latest image --vuln-type="os,library" sidwar/myapp:${{ github.sha }} > trivy-report.json
        # Publish the vulnerability scanning report as an artifact
      - name: Publish Vulnerability Scanning Report
        uses: actions/upload-artifact@v2
        with:
          name: vulnerability-report
          path: ./trivy-report.json

      # Add other steps for your scanning process (if any)

      - name: Sign Docker Image
        uses: docker-slim/docker-sign-action@v0.2
        with:
          image: sidwar/myapp:${{ github.sha }}
          username: sidwar
          password: ${{ secrets.DOCKER_PASSWORD }}
          passphrase: ${{ secrets.PASSPHRASE }}
          repository: myapp


